name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v2
      - name: Cache CondaPkg
        id: cache-condaPkg
        uses: actions/cache@v4
        env:
          cache-name: cache-condapkg
        with:
          path: |
            .CondaPkg
            docs/.CondaPkg
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('docs/CondaPkg.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
