name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

env:
  PYTHON: "Conda" # use Julia's packaged Conda build for installing packages

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/julia-buildpkg@latest
      - name: Setup Conda
        run: |
          using Pkg
          Pkg.instantiate()
          using Conda
          # https://discourse.julialang.org/t/conda-not-installing-matplotlib-for-pyplot/96813/2
          Conda.add("conda==23.1.0")
        shell: julia --color=yes --project {0}
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
